#!/bin/sh

ln -sf ${XDG_CONFIG_HOME}/sxhkd/bspwm_norm \
    ${XDG_CONFIG_HOME}/sxhkd/wm_norm
ln -sf ${XDG_CONFIG_HOME}/sxhkd/wm_norm \
    ${XDG_CONFIG_HOME}/sxhkd/sxhkdrc
sxhkd &

ln -sf ${XDG_CONFIG_HOME}/polybar/bspwm \
    ${XDG_CONFIG_HOME}/polybar/config
polybar main &
[ -n "$MONITOR1" ] && polybar secondary &

st -c dd -n ddterm -T "Terminal" -e sh -c 'tmux attach-session -t default; exec zsh' &
sleep 3
togmap.sh -l ddterm

st -e sh -c 'tmux attach-session -t default; exec zsh' &
