#!/bin/sh

bspc config border_width         1
bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config gapless_monocle      true
bspc config split_ratio          0.50
bspc config window_gap           20

bspc monitor ${MONITOR0:-focused} -d \
    Scratch WWW YouTube
[ -z $MONITOR1 ] || bspc monitor $MONITOR1 -d \
    Discord

bspc desktop Scratch -l monocle

bspc rule -a Gxmessage:*:* state=floating
bspc rule -a Yad:*:* state=floating
bspc rule -a dd:*:* state=floating
bspc rule -a dd:ddterm:* state=fullscreen
bspc rule -a discord:*:* desktop=Discord
bspc rule -a mupen64plus:*:* state=floating
