#!/bin/sh

FOREGROUND=$(xrdb -query | grep -m 1 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep -m 1 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep -m 1 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep -m 1 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep -m 1 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep -m 1 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep -m 1 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep -m 1 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep -m 1 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep -m 1 'color7:'| awk '{print $NF}')
DARK_GREY=$(xrdb -query | grep -m 1 'color8:'| awk '{print $NF}')
LIGHT_RED=$(xrdb -query | grep -m 1 'color9:'| awk '{print $NF}')
LIGHT_GREEN=$(xrdb -query | grep -m 1 'color10:'| awk '{print $NF}')
LIGHT_YELLOW=$(xrdb -query | grep -m 1 'color11:'| awk '{print $NF}')
LIGHT_BLUE=$(xrdb -query | grep -m 1 'color12:'| awk '{print $NF}')
LIGHT_MAGENTA=$(xrdb -query | grep -m 1 'color13:'| awk '{print $NF}')
LIGHT_CYAN=$(xrdb -query | grep -m 1 'color14:'| awk '{print $NF}')
LIGHT_GREY=$(xrdb -query | grep -m 1 'color15:'| awk '{print $NF}')

bspc config normal_border_color "$BLACK"
bspc config active_border_color "$BLACK"
bspc config focused_border_color "$YELLOW"
bspc config presel_feedback_color "$LIGHT_GREY"
